"use strict";

export const wordBank = {
  academic: [
    "therefore",
    "however",
    "nevertheless",
    "consequently",
    "furthermore",
    "moreover",
    "thus",
    "hence",
    "accordingly",
    "subsequently",
    "conversely",
    "notwithstanding",
    "albeit",
    "whereas",
    "hitherto",
    "heretofore",
    "ergo",
    "vis-à-vis",
    "aforementioned",
    "herein",
    "pursuant",
    "insofar",
    "wherein",
    "whereby",
    "herewith",
    "henceforth",
    "ipso facto",
    "a priori",
    "a posteriori",
    "inter alia",
    "prima facie",
    "de facto",
    "per se",
    "ad hoc",
    "quid pro quo",
    "sine qua non",
    "mutatis mutandis",
    "ceteris paribus",
    "viz.",
    "i.e.",
    "e.g.",
    "et al.",
    "ibid.",
    "op. cit.",
    "cf.",
    "empirical",
    "theoretical",
    "conceptual",
    "paradigm",
    "methodology",
    "epistemology",
    "ontology",
    "axiom",
    "hypothesis",
    "thesis",
    "antithesis",
    "synthesis",
    "dialectic",
    "heuristic",
    "hermeneutic",
    "phenomenology",
    "existentialism",
    "positivism",
    "empiricism",
    "rationalism",
    "deductive",
    "inductive",
    "syllogism",
    "premise",
    "conclusion",
    "corollary",
    "postulate",
    "theorem",
    "lemma",
    "proposition",
    "axiom",
    "tautology",
    "fallacy",
    "syllogistic",
    "cogent",
    "valid",
    "sound",
    "inference",
    "implication",
    "entailment",
    "contingent",
    "necessary",
    "sufficient",
    "a fortiori",
    "modus ponens",
    "modus tollens",
    "ad infinitum",
    "reductio ad absurdum",
    "petitio principii",
    "non sequitur",
    "argumentum ad hominem",
    "post hoc ergo propter hoc",
    "circular reasoning",
    "false dichotomy",
    "straw man",
    "correlation",
    "causation",
    "confounding",
    "variable",
    "constant",
    "dependent",
    "independent",
    "control",
    "experimental",
    "quasi-experimental",
    "longitudinal",
    "cross-sectional",
    "cohort",
    "sample",
    "population",
    "parametric",
    "non-parametric",
    "regression",
    "analysis",
    "variance",
    "coefficient",
    "significance",
    "null hypothesis",
    "alternative hypothesis",
    "p-value",
    "confidence interval",
    "standard deviation",
    "standard error",
    "mean",
    "median",
    "mode",
    "skewness",
    "kurtosis",
    "distribution",
    "normal distribution",
    "chi-square",
    "t-test",
    "ANOVA",
    "MANOVA",
    "factor analysis",
    "cluster analysis",
    "discriminant analysis",
    "multivariate",
    "univariate",
    "bivariate",
    "qualitative",
    "quantitative",
    "mixed methods",
    "triangulation",
    "validity",
    "reliability",
    "generalizability",
    "replicability",
    "falsifiability",
    "operationalization",
    "construct",
    "variable",
    "indicator",
    "measurement",
    "scale",
    "nominal",
    "ordinal",
    "interval",
    "ratio",
    "Likert scale",
    "semantic differential",
    "content analysis",
    "discourse analysis",
    "grounded theory",
    "ethnography",
    "phenomenography",
    "action research",
    "case study",
    "meta-analysis",
    "systematic review",
    "literature review",
    "annotated bibliography",
    "abstract",
    "introduction",
    "methodology",
    "results",
    "discussion",
    "conclusion",
    "implications",
    "limitations",
    "future research",
    "references",
    "appendix",
    "footnote",
    "endnote",
    "citation",
    "bibliography",
    "plagiarism",
    "paraphrase",
    "quotation",
    "in-text citation",
    "parenthetical citation",
    "et cetera",
    "exempli gratia",
    "id est",
    "videlicet",
    "nota bene",
    "sic",
    "passim",
    "verbatim",
    // ... continue adding more academic words ...
  ],
  casual: [
    "like",
    "yeah",
    "stuff",
    "thing",
    "kinda",
    "cool",
    "awesome",
    "totally",
    "super",
    "crazy",
    "dude",
    "bro",
    "man",
    "guy",
    "girl",
    "chill",
    "hang out",
    "grab",
    "catch up",
    "hit up",
    "no worries",
    "my bad",
    "oops",
    "whoops",
    "yikes",
    "holy cow",
    "holy moly",
    "oh my gosh",
    "geez",
    "dang",
    "sweet",
    "rad",
    "sick",
    "wicked",
    "dope",
    "lit",
    "fire",
    "bomb",
    "legit",
    "epic",
    "savage",
    "salty",
    "extra",
    "basic",
    "slay",
    "flex",
    "low-key",
    "high-key",
    "sus",
    "cap",
    "no cap",
    "bet",
    "fam",
    "squad",
    "crew",
    "vibe",
    "mood",
    "feels",
    "tea",
    "spill the tea",
    "snatched",
    "on fleek",
    "gucci",
    "bougie",
    "boujee",
    "yolo",
    "fomo",
    "tl;dr",
    "idk",
    "tbh",
    "imo",
    "imho",
    "lol",
    "lmao",
    "rofl",
    "wtf",
    "af",
    "rn",
    "nvm",
    "hmu",
    "brb",
    "gtg",
    "ttyl",
    "irl",
    "jk",
    "smh",
    "fyi",
    "asap",
    "aka",
    "diy",
    "yada yada",
    "blah blah",
    "yadda yadda",
    "meh",
    "whatevs",
    "anywho",
    "anyways",
    "welp",
    "okie dokie",
    "okurr",
    "aight",
    "aiight",
    "ight",
    "sup",
    "wassup",
    "wazzup",
    "yo",
    "heya",
    "howdy",
    "hiya",
    "gimme",
    "lemme",
    "gonna",
    "wanna",
    "gotta",
    "dunno",
    "ain't",
    "y'all",
    "yinz",
    "youse",
    "innit",
    "init",
    "totes",
    "probs",
    "prolly",
    "def",
    "obvs",
    "obvi",
    "preggo",
    "preggers",
    "bae",
    "boo",
    "hun",
    "honey",
    "sweetie",
    "bestie",
    "bff",
    "homie",
    "dawg",
    "peeps",
    "folks",
    "fam",
    "squad",
    "gang",
    "crew",
    "ride or die",
    "goals",
    "ship",
    "stan",
    "mood",
    "same",
    "big mood",
    "whole mood",
    "big same",
    "whole same",
    "vibe check",
    "no joke",
    "for real",
    "straight up",
    "deadass",
    "facts",
    "word",
    "preach",
    "spill",
    "tea",
    "shade",
    "snatched",
    "wig",
    "cancelled",
    "pressed",
    "triggered",
    "shook",
    "dead",
    "deceased",
    "weak",
    "ded",
    "rip",
    "yeet",
    "bet",
    "say less",
    "slaps",
    "bops",
    "bangers",
    "jams",
    "banger",
    "slapper",
    "bop",
    "jam",
    "hit",
    "banger",
    "slaps hard",
    "goes hard",
    "hits different",
    "bussin",
    "fire",
    "flames",
    "heat",
    "fuego",
    "gas",
    "trash",
    "garbage",
    "wack",
    "lame",
    "bogus",
    "janky",
    "sketchy",
    "sus",
    "suss",
    "suspect",
    "shady",
    "lowkey",
    "highkey",
    "key",
    "major key",
    "minor key",
    "clutch",
    "clutched",
    "choked",
    "tilted",
    "salty",
    "toxic",
    "cap",
    "no cap",
    "facts",
    "fax",
    "big facts",
    "big fax",
    "straight facts",
    "straight fax",
    "periodt",
    "period",
    "full stop",
    "full send",
    "send it",
    "yolo",
    // ... continue adding more casual words ...
  ],
};
